# Generated by Django 4.2.4 on 2023-09-11 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicomedic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('title', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Appointments', to='psicomedic.patient')),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Appointments', to='psicomedic.psychologist')),
            ],
        ),
    ]
